# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactsInfoNoticeMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendMessage_pb2 as FriendMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43ontactsInfoNoticeMessage.proto\x1a\x13\x46riendMessage.proto\"N\n\x19\x43ontactsInfoNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x1f\n\x07\x46riends\x18\x02 \x03(\x0b\x32\x0e.FriendMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContactsInfoNoticeMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTACTSINFONOTICEMESSAGE._serialized_start=56
  _CONTACTSINFONOTICEMESSAGE._serialized_end=134
# @@protoc_insertion_point(module_scope)
