# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendTalkNoticeMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46riendTalkNoticeMessage.proto\"N\n\x17\x46riendTalkNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08\x46riendId\x18\x03 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x06 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendTalkNoticeMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRIENDTALKNOTICEMESSAGE._serialized_start=33
  _FRIENDTALKNOTICEMESSAGE._serialized_end=111
# @@protoc_insertion_point(module_scope)
