# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransportMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16TransportMessage.proto\x1a\x19google/protobuf/any.proto\"\x8f\x01\n\x10TransportMessage\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x13\n\x0b\x41\x63\x63\x65ssToken\x18\x02 \x01(\t\x12\x1d\n\x07MsgType\x18\x03 \x01(\x0e\x32\x0c.EnumMsgType\x12%\n\x07\x43ontent\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x14\n\x0cRefMessageId\x18\x05 \x01(\x03*j\n\x0b\x45numMsgType\x12\x0e\n\nUnknownMsg\x10\x00\x12\x11\n\x0cHeartBeatReq\x10\xe9\x07\x12\x13\n\x0eMsgReceivedAck\x10\xea\x07\x12\n\n\x05\x45rror\x10\xeb\x07\x12\x17\n\x12WeChatOnlineNotice\x10\xfc\x07*\x18\n\nEnumGender\x12\n\n\x06gender\x10\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TransportMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENUMMSGTYPE._serialized_start=199
  _ENUMMSGTYPE._serialized_end=305
  _ENUMGENDER._serialized_start=307
  _ENUMGENDER._serialized_end=331
  _TRANSPORTMESSAGE._serialized_start=54
  _TRANSPORTMESSAGE._serialized_end=197
# @@protoc_insertion_point(module_scope)
