# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatOnlineNoticeMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fWeChatOnlineNoticeMessage.proto\x1a\x16TransportMessage.proto\"\x81\x01\n\x19WeChatOnlineNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08WeChatNo\x18\x02 \x01(\t\x12\x12\n\nWeChatNick\x18\x03 \x01(\t\x12\x1b\n\x06Gender\x18\x04 \x01(\x0e\x32\x0b.EnumGender\x12\x0f\n\x07\x43ountry\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeChatOnlineNoticeMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WECHATONLINENOTICEMESSAGE._serialized_start=60
  _WECHATONLINENOTICEMESSAGE._serialized_end=189
# @@protoc_insertion_point(module_scope)
